<?php
return [
    'dashboard' => [
        'label' => 'Executive Dashboard',
        'description' => 'KPIs, revenue pulse, and operational alerts for leadership.',
        'icon' => 'bi-graph-up-arrow',
        'category' => 'Core Platform Essentials',
        'locked' => true,
    ],
    'pos' => [
        'label' => 'Retail POS',
        'description' => 'Counter sales, quick tenders, discounts, and drawer controls.',
        'icon' => 'bi-cart-plus',
        'category' => 'Sales Counters',
    ],
    'sales' => [
        'label' => 'Sales History & Registers',
        'description' => 'Register audit, receipt settings, promotions, and void workflows.',
        'icon' => 'bi-journal-check',
        'category' => 'Sales Counters',
    ],
    'customers' => [
        'label' => 'Customers & Loyalty',
        'description' => 'CRM tools, loyalty balances, and communication history.',
        'icon' => 'bi-people',
        'category' => 'Sales Counters',
    ],
    'inventory' => [
        'label' => 'Inventory & Catalog',
        'description' => 'Products, stock counts, GRNs, and multi-location transfers.',
        'icon' => 'bi-boxes',
        'category' => 'Back Office & Governance',
    ],
    'restaurant' => [
        'label' => 'Restaurant Suite',
        'description' => 'Dine-in orders, reservations, table management, and KDS.',
        'icon' => 'bi-cup-hot',
        'category' => 'Hospitality & Guest Ops',
    ],
    'bar' => [
        'label' => 'Bar & Beverage',
        'description' => 'Tots, shots, portions, cocktail recipes, and yield tracking.',
        'icon' => 'bi-cup-straw',
        'category' => 'Hospitality & Guest Ops',
    ],
    'rooms' => [
        'label' => 'Rooms & Accommodation',
        'description' => 'Room inventory, folios, invoices, and stay extensions.',
        'icon' => 'bi-building',
        'category' => 'Hospitality & Guest Ops',
    ],
    'housekeeping' => [
        'label' => 'Housekeeping Board',
        'description' => 'Room turns, inspections, and task dispatch for staff.',
        'icon' => 'bi-broom',
        'category' => 'Hospitality & Guest Ops',
    ],
    'maintenance' => [
        'label' => 'Maintenance Desk',
        'description' => 'Issue intake, technician routing, and resolution tracking.',
        'icon' => 'bi-tools',
        'category' => 'Hospitality & Guest Ops',
    ],
    'delivery' => [
        'label' => 'Delivery & Dispatch',
        'description' => 'Rider assignments, live tracking, and pricing rules.',
        'icon' => 'bi-truck',
        'category' => 'Logistics & Field Ops',
    ],
    'events' => [
        'label' => 'Events & Banquets',
        'description' => 'Weddings, conferences, venue bookings, and event services.',
        'icon' => 'bi-calendar-event',
        'category' => 'Hospitality & Guest Ops',
    ],
    'security' => [
        'label' => 'Security Management',
        'description' => 'Guard scheduling, patrols, incidents, and visitor logs.',
        'icon' => 'bi-shield-check',
        'category' => 'Operations & Safety',
    ],
    'hr' => [
        'label' => 'HR & Employees',
        'description' => 'Payroll, leave management, performance reviews, and training.',
        'icon' => 'bi-person-badge',
        'category' => 'Back Office & Governance',
    ],
    'reports' => [
        'label' => 'Business Reports',
        'description' => 'Operational analytics, exports, and scheduled reports.',
        'icon' => 'bi-file-earmark-bar-graph',
        'category' => 'Back Office & Governance',
    ],
    'accounting' => [
        'label' => 'Accounting & Finance',
        'description' => 'Ledger-ready exports, balance sheet, P&L, and tax packs.',
        'icon' => 'bi-calculator',
        'category' => 'Back Office & Governance',
    ],
    'locations' => [
        'label' => 'Locations & Branches',
        'description' => 'Geo-aware branches, stock routing, and cash controls per site.',
        'icon' => 'bi-geo-alt',
        'category' => 'Back Office & Governance',
    ],
    'users' => [
        'label' => 'User & Access Control',
        'description' => 'Role assignments, permissions, and compliance logs.',
        'icon' => 'bi-person-gear',
        'category' => 'Admin & Compliance',
    ],
    'settings' => [
        'label' => 'System Configuration',
        'description' => 'Branding, fiscal parameters, integrations, and toggles.',
        'icon' => 'bi-gear',
        'category' => 'Admin & Compliance',
        'locked' => true,
    ],
];
